import Head from 'next/head'
import styles from '../styles/Home.module.css'
import socket from '../services/socketio';
import { useEffect, useState } from 'react';

export default function Home() {
  const [messages, setMessages] = useState(["Andre", "Artur"]);
  const [text, setText] = useState('');

  useEffect(() => {
    socket.on('messagesChat', info => {
      setMessages(info);
    })
  },[])

  function mandarMensagem () {
    if(text !== ''){
      socket.emit("novaMensagem", text);
      setText('');
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Chatzin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Chatzin
        </h1>
        <div className={styles.chatArea}>
          { messages.length > 0 &&
            messages.map((msg, index) => 
              {return <p key={index}>{msg}</p>}
            )
          }  
        </div>
        <input 
          placeholder="Mande uma mensagem"
          value={text}
          onChange={(e) => setText(e.target.value)}
        />
        <button onClick={() => mandarMensagem()}>Mandar mensagem</button>
      </main>
    </div>
  )
}
